### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jackogip**
Added links to demo videos.

To make it easier for people to get started with microros in e2studio

### CODE REVIEW

**Comment by Acuadros95** [comment]
Nice contribution!

Could you move the video table right under the available demos one?
Also, a few words could be added, like: `A set of recorded demos are available with step by step explanations`

**Review by Jackogip — COMMENTED** [review]
Updated with @Acuadros95 suggestions

**Review by Acuadros95 — APPROVED** [review]
LGTM, thanks again for the contribution!

**Comment by Acuadros95** [comment]
@mergify backport rolling humble

**Pull request merged**
